# © 2025 Mouvement Français pour un Revenu de Base http://www.revenudebase.info
#
# SPDX-License-Identifier: Apache-2.0+
# SPDX-FileContributor:    Fabien FURFARO
# SPDX-FileContributor:    Henri  GEIST

services:
  backend:
    container_name: ${INSTANCE_NAME}_rdb_simulator_backend
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - db_backend
      - backend_frontend
    restart: unless-stopped

  frontend:
    container_name: ${INSTANCE_NAME}_rdb_simulator_frontend
    build: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    networks:
      - backend_frontend
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.services.frontend_service.loadbalancer.server.port=8501"
      - "traefik.http.routers.frontend.service=frontend_service"
    restart: unless-stopped

  db:
    container_name: ${INSTANCE_NAME}_rdb_simulator_db
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - db_backend
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  db_backend:
  backend_frontend:
  traefik:
    name: ${TRAEFIK_NETWORK_NAME}
    external: true
