# © 2025 Mouvement Français pour un Revenu de Base http://www.revenudebase.info
#
# SPDX-License-Identifier: Apache-2.0+
# SPDX-FileContributor:    Fabien FURFARO

[theme]
primaryColor = "#2980B9"                # Couleur principale (boutons, surlignages)
backgroundColor = "#F7F9FC"             # Couleur de fond du contenu
secondaryBackgroundColor = "#FFFFFF"    # Fond secondaire (sidebar, encarts)
textColor = "#2C3E50"                   # Couleur du texte principal
font = "sans serif"                     # Police utilisée ("serif", "sans serif", "monospace")

[client]
toolbarMode = "auto"

[server]
enableCORS = false
enableXsrfProtection = false
headless = true
port = 8501
